-- NEED TO BE POPULATED DAILY

-- User revenue by created by each user within day/month/week

INSERT INTO {period_type}_USER_REVENUE(DATE, USER_ID, AMOUNT)
SELECT { TO_DATE(EVENT_TIMESTAMP) } AS DATE, USER_ID, SUM(USD_COST) FROM IN_APP_PURCHASE_LOG_SERVER PLS
WHERE { TO_DATE(EVENT_TIMESTAMP) } = {period_key} and USER_IS_SPENDER = true
GROUP BY { TO_DATE(EVENT_TIMESTAMP) }, USER_ID; 
